### ISSUE TITLE
Checking if a specific permission is already set

### ISSUE THREAD

**Issue by EiTaNBaRiBoA** [WaseemSabir/BatteryPermissionHelper#11]
**Is your feature request related to a problem? Please describe.**
If it's possible to know if the user already set the permission for "No restriction" for example on Miui and getting the results back

**Describe the solution you'd like**
A string/enum for understanding if the set the wanted permission

**Describe alternatives you've considered**
The alternative is just to believe the user if he set the desired permission

**Comment by WaseemSabir** [comment]
@EiTaNBaRiBoA The library contains activities that can be used to set the relevant permission on different handsets. There is currently no way of knowing if the user has actually enabled the permission because this is not standard permission, it is specific to the handset and has been implemented in hacky(non-android) ways to give an illusion of better battery life in these handsets.

**Comment by WaseemSabir** [comment]
I would definitely be open if you could suggest some way how we can achieve this. Hacky ways work too.
